In [15]:
import pandas as pd
pd.read_csv("encoder_compress.csv")

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,y
0,-10336.5690,5035.60740,3806.3677,5923.93260,6489.7410,-2434.1987,8621.0680,2084.83470,-5657.7476,-10261.0810,0.0
1,-3768.5796,5665.02250,6270.1343,2794.57030,5835.8105,1672.7770,12491.6690,-2245.00050,-10027.5350,-3784.7576,0.0
2,-7136.0327,6979.68460,2358.5708,1497.89980,-643.4554,4192.2134,10666.7050,6008.66360,-4687.0240,2921.1626,0.0
3,3061.3306,10517.95400,-2411.7234,-1691.71240,-7851.3677,1603.9214,9739.3690,4960.29830,-7449.8410,-3791.6885,0.0
4,7347.1980,13569.15400,2704.7043,-756.96545,-11416.4820,3214.9421,9801.1740,7616.80220,-7344.6587,-1434.8829,0.0
...,...,...,...,...,...,...,...,...,...,...,...
12665,-2528.9680,-7724.15430,9314.0840,-817.13830,2716.4620,-2538.5137,16842.0880,-3859.06470,-7029.9910,-16206.0900,4.0
12666,-5658.7104,5948.88500,-7379.4526,-10449.04100,-4535.5073,-4945.7970,-6495.2134,5441.11670,-9477.1870,-9434.2340,4.0
12667,-8207.6540,10717.48000,1562.3373,4196.99850,-16364.2610,-15001.3420,-721.5108,3099.39180,-7429.2440,-9556.9530,4.0
12668,-8806.6875,685.70966,5495.4937,-3105.54030,-4952.9100,-1103.6447,7569.3345,185.13426,-10987.2540,-3669.0781,4.0
12669,-5940.5720,-928.02850,7468.5093,761.02747,-1078.7130,-2469.5480,12418.7140,-726.74210,-10066.9110,-4051.7397,4.0

In [7]:
pd.read_csv("../20/dataset1.csv")

,Unnamed: 0,x0,x1,x2,x3,x4,x5,x6,x7,x8,...,x39,x40,x41,x42,x43,x44,x45,x46,x47,y
0,0,2232.0,3792.0,3917.0,2988.0,3670.0,4589.0,6886.0,8869.0,10590.0,...,3708.0,2676.0,2525.0,3442.0,7070.0,6718.0,4690.0,1461.0,198.0,0
1,1,128.0,912.0,2975.0,5746.0,8667.0,6682.0,4602.0,6281.0,6154.0,...,2461.0,6211.0,8852.0,4951.0,4200.0,4660.0,3481.0,2030.0,316.0,0
2,2,963.0,2995.0,4850.0,5382.0,4817.0,3574.0,3197.0,2994.0,4031.0,...,4331.0,4006.0,2823.0,2658.0,4698.0,4645.0,4965.0,12866.0,6945.0,0
3,3,5233.0,3251.0,6838.0,7378.0,3221.0,1437.0,1533.0,1751.0,1864.0,...,1308.0,1655.0,1918.0,1913.0,2083.0,2146.0,1452.0,510.0,22994.0,0
4,4,1670.0,3982.0,7710.0,6149.0,2921.0,1903.0,1171.0,765.0,623.0,...,934.0,630.0,552.0,486.0,416.0,538.0,273.0,215.0,34315.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12665,4816,367.0,573.0,1813.0,3326.0,5551.0,8604.0,8753.0,16222.0,15051.0,...,7673.0,6603.0,12530.0,18991.0,6336.0,909.0,57.0,11.0,0.0,4
12666,4817,7060.0,35431.0,3555.0,2914.0,2349.0,1785.0,1611.0,1579.0,1574.0,...,2637.0,2456.0,2181.0,1853.0,1372.0,847.0,427.0,213.0,11.0,4
12667,4818,36006.0,9917.0,6727.0,4848.0,2816.0,1376.0,740.0,351.0,158.0,...,4181.0,3149.0,2296.0,1691.0,1333.0,1052.0,1096.0,1028.0,283.0,4
12668,4819,3083.0,5133.0,6834.0,7980.0,9130.0,9267.0,6038.0,4303.0,3279.0,...,10424.0,9912.0,7061.0,5337.0,3349.0,2079.0,1529.0,1227.0,2535.0,4
12669,4820,1812.0,3742.0,5634.0,7536.0,10708.0,8948.0,7590.0,6386.0,4326.0,...,6933.0,7598.0,8552.0,7719.0,5721.0,3650.0,1592.0,957.0,1758.0,4

In [21]:
pd.read_csv("pca_compress.csv")

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,y
0,-8440.711137,-6197.391493,-652.637084,-2722.516399,3616.457732,793.001158,-3824.946673,3232.969756,8582.714786,3334.351052,0
1,-5589.504628,-9655.185167,-3104.109519,-1635.619481,1919.299650,1608.822967,-2734.798787,-3364.486348,3311.616550,1601.419590,0
2,7461.913583,-7877.569957,4926.265832,8136.998819,-4310.876278,-609.760644,-281.660429,-1845.702520,2720.906690,-785.180944,0
3,31529.649889,8800.632562,-6371.130502,-475.714796,6188.696371,2585.038985,-3040.672529,-3125.350978,1867.112335,-993.360596,0
4,51299.536757,8602.544754,-14030.801511,1796.247557,8333.873331,1977.950137,-2361.702314,-1327.973809,1162.005415,-146.485318,0
...,...,...,...,...,...,...,...,...,...,...,...
12665,-10994.712677,-14841.582619,-8977.571489,-18676.978577,-6771.739157,-7751.276222,-2103.857979,3898.580984,-1065.815579,4096.170071,4
12666,-8929.028580,32574.371101,11113.062316,-4844.852419,1496.556882,-2204.224810,-18802.408319,1318.355449,-7933.812756,-13044.749087,4
12667,-11110.219137,28068.145064,-397.038085,893.572757,555.307493,-1583.117709,16520.357353,3130.194152,4279.617862,5737.072348,4
12668,-7555.041719,-3538.893933,-11508.769721,-1876.433671,-5490.409610,1471.531479,950.362565,480.914262,-2522.787207,-1849.936745,4
12669,-7863.297680,-7618.887767,-9694.200256,-5028.721052,-3761.636415,406.767583,-179.373103,-1670.923895,-3450.653819,2788.528558,4